apiVersion: skaffold/v2beta16
kind: Config

build:
  local:
    push: false
    useBuildkit: true

  artifacts:
  - image: meetings
    context: packages/meetings
    docker: &docker
      dockerfile: build/nest-prisma.dockerfile
      secret:
        id: npmrc
        src: .npmrc
    sync: &sync
      manual:
        - src: src/**/*.ts
          dest: .

        # TODO: could consider a tigher dev loop on library work with something like
        # - src: '../shared/dist/*'
        #   dest: node_modules/@jamesdabbs/nest-platform/dist
        # - src: tmp/restart.txt
        #   dest: tmp/restart.txt

  - image: minutes
    context: packages/minutes
    docker:
      <<: *docker
      dockerfile: build/nest.dockerfile
    sync: *sync

  - image: schedule
    context: packages/schedule
    docker:
      <<: *docker
      dockerfile: build/nest.dockerfile
    sync: *sync

  - image: slack
    context: packages/slack
    docker:
      <<: *docker
      dockerfile: build/nest.dockerfile
    sync: *sync

deploy:
  kubectl:
    flags:
      global:
        - --namespace=friday
    manifests:
    # Probably want to manually install these into the kafka namespace
    # and not have them managed by Skaffold
    # - packages/infra/vendor/strimzi-operator.yaml
    # - packages/infra/vendor/kafka-persistent-single.yaml
    - packages/infra/dist/infra.k8s.yaml
